### ISSUE TITLE
Linterをつけたい。

### ISSUE THREAD

**Issue by okash1n** [sre-next/corporate-regulations#8]
GitHub Actionsでやる？

**Comment by sogaoh** [comment]
a. .vscode/settings.json で保存前に自動でかけるか 
b. デプロイ前に GitHub Actions で補正するか

a. は settings.json を無効化するとすり抜けができてしまうところが懸念
b. は GitHub Actions 内で push してあげる必要がある

確実そうなのは b
手っ取り早くやるなら a
という感じですかね・・・

**Comment by okash1n** [comment]
bの方が理想的

**Comment by okash1n** [comment]
特にミスりがちな「規定」と「規程」とか明示的にチェックできるようにしたい（後者が正）

**Comment by okash1n** [comment]
GitHub ActionsでZennブログの校正を自動化してみた
https://zenn.dev/yuta28/articles/blog-lint-ci-reviewdog

**Comment by okash1n** [comment]
ひとまず以下と同じ設定を施してみようかと思う

markdownlintとtextlintでMarkdownを校正する
https://zenn.dev/3w36zj6/scraps/27c493fa1ec611

**Comment by okash1n** [comment]
こちらで追加済
https://github.com/sre-next/corporate-regulations/pull/11
